/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.ui;

import com.server.remote.*;
import com.server.model.*;
import com.server.model.player;
import com.server.remote.RemoteInterface;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.rmi.AccessException;
import java.rmi.Naming;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 * 
 * @author Sangeeth Nawarathna
 */
public class SignUp extends javax.swing.JFrame {
    com.server.model.player Player;
    Registry regi = null;
    
    
    /**
     * Creates new form SignUP
     */
    public SignUp() {
        initComponents();
        lblError.setVisible(false);
        
        Player = new player();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginNow = new javax.swing.JLabel();
        already = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        chkShow = new javax.swing.JCheckBox();
        btnSignUp = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        loginNow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginNow.setForeground(new java.awt.Color(255, 255, 255));
        loginNow.setText("Login.");
        loginNow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginNowMouseMoved(evt);
            }
        });
        loginNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginNowMouseClicked(evt);
            }
        });
        getContentPane().add(loginNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        already.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        already.setForeground(new java.awt.Color(255, 255, 255));
        already.setText("Already have an account?");
        getContentPane().add(already, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 110, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 240, 40));

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 240, 40));

        txtConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 240, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 240, 40));

        chkShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkShow.setForeground(new java.awt.Color(255, 255, 255));
        chkShow.setText("Show Passwords");
        chkShow.setOpaque(false);
        chkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowActionPerformed(evt);
            }
        });
        getContentPane().add(chkShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 200, -1));

        btnSignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSignUpMouseMoved(evt);
            }
        });
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        btnSignUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSignUpKeyPressed(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Please check the passwords again!");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vv.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is to signup. System will take inputs name, username, password and confirm password.
     * if password and confirm password inputs are matching, then system will redirect to login.
     */
    public void signup(){
        String name = txtName.getText().trim();
        String uname = txtUserName.getText().trim();
        String pwd = txtPassword.getText().trim();
        String cpw = txtConfirmPassword.getText().trim();

        Player.setName(name);
        Player.setUsername(uname);
        Player.setPassword(pwd);

        if (pwd.equals(cpw)) {
            try {
                regi = LocateRegistry.getRegistry("localhost", 1099);
                RemoteInterface inter = null;
                try {
                    inter = (RemoteInterface) regi.lookup("RemoteServer");
                } catch (NotBoundException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (AccessException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }

                inter.newPlayer(name, uname, pwd);
                JOptionPane.showMessageDialog(null, "Profile Created. Happy gaming!");
                this.setVisible(false);
                new login().setVisible(true);
                System.err.println("User added");
            } catch (RemoteException ex) {
                System.out.println("Exception " + ex);
            }

        } else {
            lblError.setVisible(true);
        }
    }
    
    /**
     * If user checked th the check box, user can see the typed password
     * @param evt Action Event
     */
    private void chkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowActionPerformed
        // TODO add your handling code here:
        if(chkShow.isSelected()){
            txtPassword.setEchoChar((char)0);
            txtConfirmPassword.setEchoChar((char)0);
            
        }else{
            txtPassword.setEchoChar(('*'));
            txtConfirmPassword.setEchoChar(('*'));
        }
    }//GEN-LAST:event_chkShowActionPerformed

    /**
     * The signup() method will run if user click the button with mouse pointer.
     * @param evt action event
     */
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

       signup();
 
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSignUpMouseClicked
    
    /**
     * Using the up and down arrow keys, the user can move between text fields
     * @param evt Key Event
     */
    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtPassword.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    /**
     * Using the up and down arrow keys, the user can move between text fields
     * @param evt Key Event
     */
    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtConfirmPassword.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtUserName.requestFocus();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyReleased

    /**
     * Using the up and down arrow keys, the user can move between text fields
     * @param evt key event
     */
    private void txtConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnSignUp.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtConfirmPasswordKeyPressed

    
    /**
     * The signup() method will run if user click the button by pressing enter.
     * @param evt Key Event
     */
    private void btnSignUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSignUpKeyPressed
        signup();

    }//GEN-LAST:event_btnSignUpKeyPressed

    
    /**
     * Using the up and down arrow keys, the user can move between text fields
     * @param evt Key event
     */
    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtUserName.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * If user already have user account, user can click on login label and jump in to login UI
     * @param evt Mouse Event
     */
    private void loginNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_loginNowMouseClicked

    
    /**
     * If user keep the mouse pointer on the label login ,pointer will change in to hand cursor.
     * @param evt Mouse Event
     */
    private void loginNowMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNowMouseMoved
        // TODO add your handling code here:
        loginNow.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_loginNowMouseMoved

    private void btnSignUpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseMoved
        // TODO add your handling code here:
        btnSignUp.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnSignUp.setBackground(new java.awt.Color(51, 250, 153));
        txtName.setEnabled(false);
        txtUserName.setEnabled(false);
        txtPassword.setEnabled(false);
        txtConfirmPassword.setEnabled(false);
    }//GEN-LAST:event_btnSignUpMouseMoved

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        btnSignUp.setBackground(new java.awt.Color(240, 240, 240));
        txtName.setEnabled(true);
        txtUserName.setEnabled(true);
        txtPassword.setEnabled(true);
        txtConfirmPassword.setEnabled(true);
    }//GEN-LAST:event_jLabel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel already;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox chkShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel loginNow;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
