/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.server.ui;

import com.server.remote.RemoteImplement;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.ExportException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.dbLayer.connectionMethods;
import com.dbLayer.databaseCon;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.TableModel;
/**
 * 
 * @author Sangeeth Nawarathna
 */
public class adminHome extends javax.swing.JFrame {
    Registry regi = null;
    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
        
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblUsers = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        lblSelected = new javax.swing.JLabel();
        lblserverRuning = new javax.swing.JLabel();
        btnDeleteUser = new javax.swing.JButton();
        lbluserId = new javax.swing.JLabel();
        btnshowStats = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        brnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbluserMouseClicked(evt);
            }
        });
        tblUsers.setViewportView(tbluser);

        getContentPane().add(tblUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 530, 280));

        lblSelected.setForeground(new java.awt.Color(255, 255, 255));
        lblSelected.setText("Selected user's id:");
        getContentPane().add(lblSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 20));

        lblserverRuning.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblserverRuning.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblserverRuning, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 340, 30));

        btnDeleteUser.setText("Delete Player");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 40));

        lbluserId.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbluserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 70, 20));

        btnshowStats.setText("Show Score Stats.");
        btnshowStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowStatsActionPerformed(evt);
            }
        });
        getContentPane().add(btnshowStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 40));

        btnStop.setText("Stop Server");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        getContentPane().add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 40));

        brnStart.setText("Start Server");
        brnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnStartActionPerformed(evt);
            }
        });
        getContentPane().add(brnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin panel.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is to show all the players of the game to the admin.
     */
     public void showTableData() {
         databaseCon con = new databaseCon();
        try {
            String sql = "select uid,name,username,score from user";
            PreparedStatement prep = con.databaseConnection().prepareStatement(sql);
            ResultSet rs = prep.executeQuery();
            tbluser.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(databaseCon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    
     
     /**
      * Admin can start the server with Start Server button.
      * @param evt Action Event
      */
    private void brnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnStartActionPerformed
        // TODO add your handling code here:
         try {                                         
            RemoteImplement service = new RemoteImplement();
            
            
            try {
                Registry registry = LocateRegistry.createRegistry(1099);
                registry.rebind("RemoteServer", service);
                lblserverRuning.setText("Server is running!\n");
                System.out.println("Server is runnig!\n");
            } catch (ExportException ex) {
            
                System.out.println("Exception: " +ex);
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
        Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_brnStartActionPerformed

    /**
     * Admin can stop the server with Stop Server button.
     * @param evt Action event
     */
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
                 try {                                         
            RemoteImplement service = new RemoteImplement();
            
            
            try {
                Registry registry = LocateRegistry.getRegistry(1099);
                registry.unbind("RemoteServer");
                lblserverRuning.setText("Server stopped!\n");
                System.out.println("Server stopped!\n");
                
            } catch (ExportException ex) {
               
                System.out.println("Exception: " +ex);
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
        Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnStopActionPerformed

    
    /**
     * Admin can view score statistics of the players in different ranges.
     * quickChart() method will run. Method implemented in com.dbLayer.connectionMethods
     * @param evt Action Event
     */
    private void btnshowStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowStatsActionPerformed
        // TODO add your handling code here:
        connectionMethods met = new connectionMethods();
        met.quickChart();
    }//GEN-LAST:event_btnshowStatsActionPerformed

    
    /**
     * When admin click on the certain row in table, userID will store in label.
     * @param evt  Mouse event
     */
    private void tbluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbluserMouseClicked
        // TODO add your handling code here:
        int row = tbluser.getSelectedRow();
        TableModel model = tbluser.getModel();
        lbluserId.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tbluserMouseClicked

    
    /**
     * Admin can delete selected player from the system
     * @param evt Action Event
     */
    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        
        databaseCon con = new databaseCon();

        String sql = "delete from user where uid = ?";
        try {
            PreparedStatement prep = con.databaseConnection().prepareStatement(sql);
            int uid = Integer.parseInt(lbluserId.getText());
            prep.setInt(1, uid);
            prep.execute();

            JOptionPane.showMessageDialog(null, "Successfully deleted");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        showTableData();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnStart;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnshowStats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSelected;
    private javax.swing.JLabel lblserverRuning;
    private javax.swing.JLabel lbluserId;
    private javax.swing.JScrollPane tblUsers;
    private javax.swing.JTable tbluser;
    // End of variables declaration//GEN-END:variables
}
